version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    networks:
      - postgres-network

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: anand@example.com
      PGADMIN_DEFAULT_PASSWORD: anand
    ports:
      - "81:80"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
